name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Gitpod Java Workspace Docker image
      run: docker build ./gitpod-java/ --file Dockerfile --tag gitpod-java-workspace:$(date +%s)
    - name: Tag Buil Publish Docker
      uses: AhnSeongHyun/action-tag-docker-build-push@v1.0.0
