name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Gitpod Java Workspace Docker image
      run: docker build ./gitpod-java/ --tag gitpod-java-workspace:$(date +%s)

    - name: Build the Gitpod Java Workspace Docker image
      run: docker build ./gitpod-go1.14/ --tag gitpod-go1.14-workspace:$(date +%s)

    - name: Tag Buil Publish Gitpod Java Workspace Docker image
      uses: AhnSeongHyun/action-tag-docker-build-push@v1.0.0
      with:
        repo_name: eldius/gitpod-java-workspace
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Buil Publish Gitpod Go 1.14 Workspace Docker image
      uses: AhnSeongHyun/action-tag-docker-build-push@v1.0.0
      with:
        repo_name: eldius/gitpod-go1.14-workspace
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
